name = "SymbolicsMathLink"
uuid = "7963cd39-1b62-4514-9cf0-788fb5452611"
authors = ["E. Swagel"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
